### ISSUE TITLE
Lately been getting this error

### ISSUE THREAD

**Issue by timogoosen** [alfg/blockchain#3]
querying...https://blockchain.info//address/1NznbuGSE9FcDnHrMhQDD68iEcspZCuKXQ/?format=json
expected status 2xx, got 500 Internal Server Error: Illegal character / at 342016/12/01 07:14:05 Something went wrong and I couldn't connect blockchain.info API: expected status 2xx, got 500 Internal Server Error: Illegal character / at 34

**Comment by alfg** [comment]
Hi @timogoosen, 

Can you pull the latest and try again? I just fixed the url formatting.  I'm guessing the blockchain.info api doesn't like the extra `/` in the url. 

Latest build seems to be working.
https://github.com/alfg/blockchain/commit/a28fe3e3c874b72c6d6a767aabc65597238347f7
https://travis-ci.org/alfg/blockchain/jobs/180341644

Please confirm. Thank you!
